sudo: required

services:
- docker

language: python

install:
- sudo pip install --upgrade pip
- pip install flask
- pip install pytest

script:
- pytest

after_success:
- sh .travis/deploy_dockerhub.sh
