sudo: required

services:
- docker

language: python

install:
- sudo pip install --upgrade pip
- pip install flask
- pip install pytest
- pip install requests

script:
- pytest

after_success:
- sh .travis/deploy_dockerhub.sh
– test “$TRAVIS_BRANCH” = “master” && sh .travis/deploy_heroku.sh