sudo: required

services:
- docker

language: python

install:
- sudo pip install --upgrade pip
- pip install -r requirements.txt

script:
- pytest

after_success:
- test “$TRAVIS_BRANCH” = “develop” && sh .travis/deploy_dockerhub.sh
– test “$TRAVIS_BRANCH” = “develop” && sh .travis/deploy_heroku.sh 
